### ISSUE TITLE
Numerous errors

### ISSUE THREAD

**Issue by FredChores** [JuliaData/JuliaDB.jl#309]
Hello, I’m trying to load an out-of-core dataset of around 3k wide and 3 million long. I’ve put some error logs on the Julia discourse here:
https://discourse.julialang.org/t/juliadb-loadndsparse-many-errors/30249/3

Thanks in advance.

**Comment by andreasnoack** [comment]
This isn't actionable without a reproducer or more detailed description. Please refile if either becomes available.
