### ISSUE TITLE
Test Errors for version v0.12.0 in Windows 10

### ISSUE THREAD

**Issue by caxelrud** [JuliaData/JuliaDB.jl#311]
[juliadbTest.txt](https://github.com/JuliaComputing/JuliaDB.jl/files/3857254/juliadbTest.txt)

**Comment by jpsamaroo** [comment]
This could be one of numerous Windows tempname issues; can you retry the tests on a newer version of Julia (say v1.3)?

**Comment by jpsamaroo** [comment]
Closing pending further information and follow-up.
