### ISSUE TITLE
Fix doc links

### ISSUE THREAD

**Issue by joshday** [JuliaData/JuliaDB.jl#320]
Moving the repo into the JuliaData organization caused the doc links to break.

**Comment by jmatsushita** [comment]
This is the new link https://juliadata.github.io/JuliaDB.jl/latest/

**Comment by andreasnoack** [comment]
Fixed by https://github.com/JuliaData/JuliaDB.jl/commit/897605b8dd99de54689ecb3f1867bf1a6143d4ee
