### ISSUE TITLE
JuliaDB documentation down?

### ISSUE THREAD

**Issue by clibassi** [JuliaData/JuliaDB.jl#323]
Hi all, 

I've been unable to access the JuliaDB documentation at https://juliacomputing.github.io/JuliaDB.jl/latest/ and it seems to be down for everyone, not just for me. Anyway - I thought I'd flag it for you all.

**Comment by andreasnoack** [comment]
This broke when the repo moved from JuliaComputing to JuliaData. I've fixed the paths in the README.
