### ISSUE TITLE
Master is currently failing

### ISSUE THREAD

**Issue by andreasnoack** [JuliaData/JuliaDB.jl#324]
Some dependency changes have caused tests to fail. The immediate failure in https://travis-ci.org/github/JuliaData/JuliaDB.jl is a conflict between the `transform` function of this package and the one in `OnlineStats`. Locally, I have a fix where import only the needed functions from `OnlineStats` and I'll file a PR with that. However, once the `transform` issue is fixed, I'm getting
```julia
Test Summary: | Pass  Total
flatten       |    3      3
join: Error During Test at /Users/andreasnoack/.julia/dev/JuliaDB/test/test_join.jl:19
  Test threw exception
  Expression: isequal(collect(innerjoin(+, d1, d2)), j2)
  On worker 2:
  MethodError: reduce_empty(::typeof(Base.add_sum), ::Type{Union{}}) is ambiguous. Candidates:
    reduce_empty(::typeof(Base.add_sum), ::Type{T}) where T<:Union{Int16, Int32, Int8} in Base at reduce.jl:314
    reduce_empty(::typeof(Base.add_sum), ::Type{T}) where T<:Union{UInt16, UInt32, UInt8} in Base at reduce.jl:315
  Possible fix, define
    reduce_empty(::typeof(Base.add_sum), ::Type{Union{}})
  reduce_empty at ./reduce.jl:320
  reduce_empty_iter at ./reduce.jl:347 [inlined]
  reduce_empty_iter at ./reduce.jl:346 [inlined]
```
and
```julia
(JuliaDB) pkg> add IndexedTables@0.12.4
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
  Installed IndexedTables ─ v0.12.4
   Updating `~/.julia/dev/JuliaDB/Project.toml`
  [6deec6e2] ↓ IndexedTables v0.12.6 ⇒ v0.12.4
   Updating `~/.julia/dev/JuliaDB/Manifest.toml`
  [79e6a3ab] - Adapt v1.0.1
  [6deec6e2] ↓ IndexedTables v0.12.6 ⇒ v0.12.4
  [09ab397b] ↓ StructArrays v0.4.3 ⇒ v0.4.1
  [bd369af6] ↓ Tables v1.0.4 ⇒ v0.2.11
```
is sufficient to fix the issue so it looks like some "non-breaking" releases caused this. Any ideas that could have caused this error?

**Comment by joshday** [comment]
- OnlineStats now exports `StatsBase.transform` and it didn't before.  IndexedTables should probably import it rather than have its own `transform`.

- Not sure if its the culprit, but Tables has a breaking release up above.

**Comment by andreasnoack** [comment]
>  IndexedTables should probably import it rather than have its own transform.

I agree. That is probably the rigth thing to do.

There is a different issue in CI that I didn't see locally. It looks like it's related to OnlineStats, see https://travis-ci.org/github/JuliaData/JuliaDB.jl/jobs/683267985. @joshday any ideas?

**Comment by joshday** [comment]
Hmm, something is holding back OnlineStats/OnlineStatsBase but you have a current version of LossFunctions, which has some breaking changes.

**Comment by andreasnoack** [comment]
The link was to the Julia 1.0 test so something is probably requiring Julia > 1.0. The Julia 1.4. uses OnlineStats 1.4. That run times out, https://travis-ci.org/github/JuliaData/JuliaDB.jl/jobs/683267986, but locally it gives the error mentioned in the top post. Maybe there are some deprecations that are slowing down the run or maybe compilation has slowed down.

**Comment by DilumAluthge** [comment]
Bump. Any update on this? It looks like Travis CI is still failing on `master`. See e.g.: https://github.com/JuliaData/JuliaDB.jl/pull/339
