### ISSUE TITLE
transform() doesn't overwrite when in functions

### ISSUE THREAD

**Issue by chris-german** [JuliaData/JuliaDB.jl#333]
Hi, 

I noticed that `transform()` doesn't seem to allow for a table to be overwritten when it's called within a function. For a minimum working example:

```
using JuliaDB

t = table((x = [1.0; 1.2; 1.3], z = [2.0; 2.2; 2.3])) 

function add_y!(t)
 t = transform(t, :y => (:x, :z) => row -> row[1] + row[2])
end

julia> add_y!(t)
Table with 3 rows, 3 columns:
x    z    y
─────────────
1.0  2.0  3.0
1.2  2.2  3.4
1.3  2.3  3.6

julia> t
Table with 3 rows, 2 columns:
x    z
────────
1.0  2.0
1.2  2.2
1.3  2.3
```

The table t doesn't get overwritten when it's called within a function. However, just running `t = transform(t, :y => (:x, :z) => row -> row[1] + row[2])` will create a column `:y` in t. It seems to create a copy of t that the function uses without modifying original inputted table. I haven't noticed this behavior in DataFrames.jl, so I was wondering if this is done on purpose?

**Comment by jpsamaroo** [comment]
`transform` is probably just non-mutating. The reason it works outside of the function is because you're reassigning the result of `transform` to `t`, even though the original non-transformed table still exists un-modified (you just can't access it).

**Comment by chris-german** [comment]
Thanks. Is there an available function in JuliaDB that can achieve this? Adding columns permanently to a table, or even modifying existing ones can be useful.

**Comment by AliMalik9599** [comment]
Hey @jpsamaroo @chris-german I'd be interested in trying to work on this. I am relatively new to Julia though, any advice/tips on getting started? Thanks!

**Comment by shashi** [comment]
transform returns a new table, and leaves the input table untouched. you have to do:

```julia
t = add_y!(t)
```
