### ISSUE TITLE
Make a new release of JuliaDB?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaData/JuliaDB.jl#334]
Would it be possible to make a new release of JuliaDB? There have been 13 commits to `master` since the last release (v0.12.0).

**Comment by DilumAluthge** [comment]
cc: @andreasnoack

**Comment by MaximilianJHuber** [comment]
There is, but it is not tagged on GitHub, see #312. But I am all for a little maintenance!

**Comment by jpsamaroo** [comment]
Will be fixed by #347

**Comment by jpsamaroo** [comment]
0.13.1 tagging is on the way!
