### ISSUE TITLE
Set up GitHub Actions on this repository

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaData/JuliaDB.jl#338]
It looks like GitHub Actions is not enabled for this repository.

GitHub Actions is required for the following pull requests:
- https://github.com/JuliaData/JuliaDB.jl/pull/335
- https://github.com/JuliaData/JuliaDB.jl/pull/336
- https://github.com/JuliaData/JuliaDB.jl/pull/337

In order to enable GitHub Actions, an owner of the JuliaData organization needs to take the following steps:
1. Go to [https://github.com/organizations/JuliaData/settings/actions](https://github.com/organizations/JuliaData/settings/actions). Under the "Policies" section, make sure that "All repositories" are permitted to use GitHub Actions. Under the "Local and third-party Actions" section, make sure that both local and third-party Actions are enabled.
2. Go to [https://github.com/JuliaData/JuliaDB.jl/settings/actions](https://github.com/JuliaData/JuliaDB.jl/settings/actions). Under "Actions permissions" section, in the "Local and third-party Actions" subsection, make sure that both local and third-party Actions are enabled.

**Comment by DilumAluthge** [comment]
@ararslan or @andreasnoack could you help out with this?

**Comment by jpsamaroo** [comment]
Seems like this is now working
