### ISSUE TITLE
Nullables dependency very old

### ISSUE THREAD

**Issue by grahamas** [JuliaData/JuliaDB.jl#370]
I'm not sure how to phrase this as a proper issue. It's just that after JuliaDB v0.9 there's a dependency on Nullables v0.0.8 (in the JuliaAttic) which then puts a low ceiling on the version of Compat (I can't for the life of me figure out how exactly) which limits compatibility with newer packages. For example, you can't use Optim in its v1 releases.  Maybe a marginal problem now, but it'll only get worse.

**Comment by racinmat** [comment]
Updating it would be great. CompatHelper created tons of PRs, it would be great if they ran. 
Travis fails for them, but it seems it's because of timeout, maybe some prints would fix that.

**Comment by grahamas** [comment]
Fixed by #387
