### ISSUE TITLE
@dateformat_str is not defined

### ISSUE THREAD

**Issue by jabortell** [JuliaData/JuliaDB.jl#381]
Via the docs for the `colparsers` argument from [TextParse.jl](https://www.queryverse.org/TextParse.jl/stable/#Reading-CSV-1), I am attempting to use the `dateformat""` syntax to parse a column, for example:

```julia
using JuliaDB
loadtable("big.csv", colparsers = Dict(:issue_date => dateformat"y-m-d"))
```

...but when running, the Julia REPL complains that `@dateformat_str` is not defined.

I am using `[a93385a2] JuliaDB v0.13.0`.

**Comment by shashi** [comment]
It's in `Dates` stdlib. `using Dates`
