### ISSUE TITLE
Why DataFrames this outdated

### ISSUE THREAD

**Issue by PingoLee** [JuliaData/JuliaDB.jl#396]
I need to use JuliaBD with a newer version of DataFrames. Any forecasts to update?

**Comment by jpsamaroo** [comment]
JuliaDB is basically unmaintained, but you can use Dagger.jl's `DTable` for basic operations like `map`, `reduce`, and `filter`. We'll be implementing more table operations (like joins) and out-of-core support for the `Dagger.DTable` soon!
