### ISSUE TITLE
Impossible to install JuliaDB

### ISSUE THREAD

**Issue by gameCoder101** [JuliaData/JuliaDB.jl#411]
Fedora 36 - Julia 1.7.2
------------------------------

I am new to JuliaDB. I have issues to install it:

(@v1.7) pkg> add JuliaDB
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Knet [1902f260]:
 Knet [1902f260] log:
 ├─possible versions are: 1.0.0-1.4.10 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 1.0.0-1.4.10
 ├─restricted by compatibility requirements with CuArrays [3a865a2d] to versions: [1.0.0-1.2.3, 1.3.7-1.4.10] or uninstalled, leaving only versions: [1.0.0-1.2.3, 1.3.7-1.4.10]
 │ └─CuArrays [3a865a2d] log:
 │   ├─possible versions are: 0.2.1-2.2.2 or uninstalled
 │   └─restricted by julia compatibility requirements to versions: uninstalled
 ├─restricted by compatibility requirements with CUDA [052768ef] to versions: 1.0.0-1.3.6 or uninstalled, leaving only versions: 1.0.0-1.2.3
 │ └─CUDA [052768ef] log:
 │   ├─possible versions are: 0.1.0-3.10.1 or uninstalled
 │   ├─restricted by julia compatibility requirements to versions: [2.3.0, 2.5.0-3.10.1] or uninstalled
 │   ├─restricted by compatibility requirements with LLVM [929cbde3] to versions: 3.3.3-3.10.1 or uninstalled
 │   │ └─LLVM [929cbde3] log:
 │   │   ├─possible versions are: 0.9.0-4.13.0 or uninstalled
 │   │   └─restricted by julia compatibility requirements to versions: 4.0.0-4.13.0 or uninstalled
 │   └─restricted by compatibility requirements with SpecialFunctions [276daf66] to versions: 0.1.0-2.6.3 or uninstalled, leaving only versions: uninstalled
 │     └─SpecialFunctions [276daf66] log:
 │       ├─possible versions are: 0.7.0-2.1.5 or uninstalled
 │       ├─restricted by compatibility requirements with Knet [1902f260] to versions: 0.7.0-2.1.5
 │       │ └─Knet [1902f260] log: see above
 │       ├─restricted by compatibility requirements with GLM [38e38edf] to versions: 0.7.0-1.8.5
 │       │ └─GLM [38e38edf] log:
 │       │   ├─possible versions are: 1.0.0-1.8.0 or uninstalled
 │       │   ├─restricted to versions * by an explicit requirement, leaving only versions 1.0.0-1.8.0
 │       │   └─restricted by compatibility requirements with StatsBase [2913bbd2] to versions: 1.0.0-1.4.2 or uninstalled, leaving only versions: 1.0.0-1.4.2
 │       │     └─StatsBase [2913bbd2] log:
 │       │       ├─possible versions are: 0.24.0-0.33.16 or uninstalled
 │       │       ├─restricted to versions * by an explicit requirement, leaving only versions 0.24.0-0.33.16
 │       │       └─restricted by compatibility requirements with JuliaDB [a93385a2] to versions: 0.24.0-0.32.2
 │       │         └─JuliaDB [a93385a2] log:
 │       │           ├─possible versions are: 0.9.0-0.13.1 or uninstalled
 │       │           └─restricted to versions * by an explicit requirement, leaving only versions 0.9.0-0.13.1
 │       └─restricted by compatibility requirements with Distributions [31c24e10] to versions: 0.7.0-0.10.3
 │         └─Distributions [31c24e10] log:
 │           ├─possible versions are: 0.16.0-0.25.61 or uninstalled
 │           ├─restricted to versions * by an explicit requirement, leaving only versions 0.16.0-0.25.61
 │           ├─restricted by compatibility requirements with GLM [38e38edf] to versions: 0.16.0-0.24.18
 │           │ └─GLM [38e38edf] log: see above
 │           └─restricted by compatibility requirements with Bootstrap [e28b5b4c] to versions: 0.16.0-0.23.12
 │             └─Bootstrap [e28b5b4c] log:
 │               ├─possible versions are: 2.0.0-2.3.3 or uninstalled
 │               ├─restricted by compatibility requirements with StatsBase [2913bbd2] to versions: 2.0.0-2.2.0 or uninstalled
 │               │ └─StatsBase [2913bbd2] log: see above
 │               └─restricted by compatibility requirements with StatsKit [2cb19f9e] to versions: 2.0.0-2.3.3, leaving only versions: 2.0.0-2.2.0
 │                 └─StatsKit [2cb19f9e] log:
 │                   ├─possible versions are: 0.3.0-0.3.1 or uninstalled
 │                   └─restricted to versions * by an explicit requirement, leaving only versions 0.3.0-0.3.1
 └─restricted by compatibility requirements with CUDAapi [3895d2a7] to versions: 1.3.7-1.4.10 or uninstalled — no versions left
   └─CUDAapi [3895d2a7] log:
     ├─possible versions are: 0.5.0-4.0.0 or uninstalled
     └─restricted by julia compatibility requirements to versions: uninstalled

(@v1.7) pkg>

**Comment by gameCoder101** [comment]
I heard that 'JuliaDB' is deprecated. Is that true?
Some said that I should use Mongo instead.
-------
Installed in a new environment - no errors.
-------
Even when I removed Knet, there were errors.

**Comment by jpsamaroo** [comment]
JuliaDB is deprecated, yes. Please use Dagger.jl instead; the `DTable` has most of the features you would expect, and is actively developed.

**Comment by rs7q5** [comment]
@jpsamaroo onto this. Is there a way to neatly convert the stuff that was in JuliaDB to Dagger or something so a project is no longer reliant on it? Like are there equivalent commands in Dagger that are in JuliaDB? 

I.e. I could import Dagger and then just fix the files by hand.
